name: "Packer CI - Format & Validate"

on:
  pull_request:
    branches:
      - main  # Runs on PRs to main branch (change if needed)

jobs:
  packer-check:
    name: "Packer Format & Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Build Webapp artifact
        run: |
          zip -r Webapp.zip ./

      - name: Create .env file from GitHub Secrets
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "APP_USER=${{ secrets.APP_USER }}" >> .env
          echo "APP_GROUP=${{ secrets.APP_GROUP }}" >> .env
          echo "APP_DIR=${{ secrets.APP_DIR }}" >> .env

      - name: Initialize Packer (Install Plugins)
        run: |
          packer init ubuntu_webapp.pkr.hcl

      - name: Check Packer format
        run: |
          packer fmt -check . || (echo "Packer formatting issues found. Run 'packer fmt .' to fix." && exit 1)

      - name: Validate Packer template
        run: |
          packer validate ubuntu_webapp.pkr.hcl || (echo "Packer validation failed. Fix errors before merging." && exit 1)
