name: Packer Build

on:
  push:
    branches:
      - main  # Runs only when changes are merged to the main branch

jobs:
  build_packer_image:
    name: Build Packer Image for AWS and GCP
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Install GCP CLI
        run: |
          curl -sSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /etc/apt/trusted.gpg.d/google.asc
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

      # 🔹 AWS Authentication (Static Credentials)
      - name: Authenticate AWS CLI
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region us-east-1

      # 🔹 Authenticate GCP CLI using Service Account Key
      - name: Authenticate to GCP CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
          create_credentials_file: true
          export_environment_variables: true

      - name: Run Integration Tests
        run: |
          echo "Running integration tests..."
          # Add integration test commands here (e.g., pytest, npm test, etc.)
          echo "Integration Tests Passed"

      - name: Build Application Artifact
        run: |
          echo "Building application artifact..."
          zip -r Webapp.zip ./
          echo "Application artifact created: Webapp.zip"

      - name: Create .env File
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "APP_USER=${{ secrets.APP_USER }}" >> .env
          echo "APP_GROUP=${{ secrets.APP_GROUP }}" >> .env
          echo "APP_DIR=${{ secrets.APP_DIR }}" >> .env
          echo ".env file created successfully!"

      - name: Initialize Packer
        run: |
          packer init ubuntu_webapp.pkr.hcl

      - name: Build Packer Image for AWS and GCP
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=us-east-1
          packer build -var "aws_region=us-east-1" -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" .
