name: Github action

on:
  pull_request:

env:
  HOST: ${{ secrets.HOST }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start MySQL and Configure Root Password
      run: |
        sudo service mysql start
        sleep 10  # Allow MySQL to initialize

        # Check if MySQL root password is already set
        if sudo mysql -u root -e "SELECT 1;" 2>/dev/null; then
          echo "MySQL root access confirmed without a password."
        else
          echo "Setting MySQL root password..."
          sudo mysqladmin -u root password "${{ secrets.DB_PASS }}"
        fi

    - name: Configure MySQL Database and User
      run: |
        sudo mysql -u root -p"${{ secrets.DB_PASS }}" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"
        sudo mysql -u root -p"${{ secrets.DB_PASS }}" -e "CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASS }}';"
        sudo mysql -u root -p"${{ secrets.DB_PASS }}" -e "GRANT ALL PRIVILEGES ON ${{ secrets.DB_NAME }}.* TO '${{ secrets.DB_USER }}'@'localhost';"
        sudo mysql -u root -p"${{ secrets.DB_PASS }}" -e "FLUSH PRIVILEGES;"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
      
    - name: Wait and Run Integration Test
      run: |
        sleep 15
        pytest tests/test-api.py
