name: Web App CI

on:
  pull_request:
    branches:
      - main  # Runs on PRs to main branch

jobs:
  run-tests:
    name: Run Python Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpassword  # Hardcoded since secrets are NOT supported in services
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -prootpassword"
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          sleep 30  # Adjust wait time if needed

      - name: Configure MySQL Database and User
        run: |
          echo "Setting up MySQL database and user..."
          mysql -h 127.0.0.1 -uroot -prootpassword -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
          mysql -h 127.0.0.1 -uroot -prootpassword -e "CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';"
          mysql -h 127.0.0.1 -uroot -prootpassword -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%';"
          mysql -h 127.0.0.1 -uroot -prootpassword -e "FLUSH PRIVILEGES;"
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest tests/
